# Docker Compose file for local development

services:
  mysql:
    image: arm64v8/mysql:8.0
    container_name: grocery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: groceryprices
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - grocery-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Optional: Adminer for database management
  adminer:
    image: adminer
    container_name: grocery-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - grocery-network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  grocery-network:
    driver: bridge